### ISSUE TITLE
Add position in the eye tracking stream

### ISSUE THREAD

**Issue by aspaNeuro** [emotional-cities/pluma-analysis#73]
The Glia Eye traking stream has a new vector 3 with the hiposition to where the person is looking at. This must be loaded in the dataset.
The code in [here](https://github.com/emotional-cities/pluma-analysis/blob/d31bac2c15148bd8f3cb82dd3b0b6785ae9a6fbc/pluma/stream/zeromq.py#L94C13-L121C15) should now have:
```            
('Position.X', np.single),
('Position.Y', np.single),
('Position.Z', np.single),
```

**Comment by glopesdev** [comment]
@aspaNeuro what is the difference with the `CombinedGaze` attribute defined in the existing stream?

https://github.com/emotional-cities/pluma-analysis/blob/d31bac2c15148bd8f3cb82dd3b0b6785ae9a6fbc/pluma/stream/zeromq.py#L102-L104

If it is different, and since this is also a position, we probably would need some kind of differentiating adjective to the word `Position`.

**Comment by glopesdev** [comment]
According to @aspaNeuro this was already included in `Raycast.X`, `Raycast.Y`, `Raycast.Z`.
